substitutions:
  device_name: "athom-mini-switch"
  friendly_name: "Athom Mini Switch"
  project_name: "Athom Technology.Mini Relay Switch Module"
  project_version: "2024.2"
  light_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

api:

ota:
  platform: esphome
  
logger:


mdns:
  disabled: false

web_server:
  port: 80

wifi:
  ap: {}

captive_portal:

dashboard_import:
  #package_import_url: github://athom-tech/athom-configs/athom-mini-switch.yaml
  package_import_url: github://makerwolf1/athom-configs/athom-mini-switch.yaml

button:
  - platform: restart
    name: "Restart"
  - platform: factory_reset
    name: "Reset"
    id: Reset
  - platform: safe_mode
    name: "Safe Mode"
    internal: false

output:
  - platform: gpio
    id: relay_output
    pin: GPIO13

light:
  - platform: status_led
    id: led
    name: "Blue LED"
    disabled_by_default: true
    pin:
      number: GPIO4
      inverted: true

  - platform: binary
    id: mini_relay
    output: relay_output
    name: None
    restore_mode: ${light_restore_mode}

sensor:
  - platform: uptime
    name: "Uptime Sensor"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

binary_sensor:
  # Wired switch
  - platform: gpio
    id: the_switch
    name: "Power Switch"
    disabled_by_default: true
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    on_state:
      - light.toggle: mini_relay
      - light.toggle: led
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
        then:
          - button.press: Reset

  # Button on mini switch
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: mini_relay
          - light.toggle: led
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

  - platform: status
    name: "Status"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    bssid:
      name: "Connected BSSID"
    mac_address:
      name: "Mac Address"

time:
  - platform: sntp
    id: sntp_time
